from typing import Optional, Union

class Koon:
    """Browser impersonation HTTP client with TLS/HTTP2 fingerprint spoofing."""

    def __init__(
        self,
        browser: str = "chrome",
        *,
        profile_json: Optional[str] = None,
        proxy: Optional[str] = None,
        timeout: int = 30000,
        ignore_tls_errors: bool = False,
        headers: Optional[dict[str, str]] = None,
        follow_redirects: bool = True,
        max_redirects: int = 10,
        cookie_jar: bool = True,
    ) -> None: ...
    def export_profile(self) -> str: ...
    async def get(self, url: str) -> KoonResponse: ...
    async def post(self, url: str, body: Optional[bytes] = None) -> KoonResponse: ...
    async def put(self, url: str, body: Optional[bytes] = None) -> KoonResponse: ...
    async def delete(self, url: str) -> KoonResponse: ...
    async def patch(self, url: str, body: Optional[bytes] = None) -> KoonResponse: ...
    async def head(self, url: str) -> KoonResponse: ...
    async def request(
        self, method: str, url: str, body: Optional[bytes] = None
    ) -> KoonResponse: ...
    async def websocket(
        self, url: str, headers: Optional[dict[str, str]] = None
    ) -> KoonWebSocket: ...

class KoonResponse:
    """HTTP response from a koon request."""

    @property
    def status(self) -> int: ...
    @property
    def headers(self) -> list[tuple[str, str]]: ...
    @property
    def body(self) -> bytes: ...
    @property
    def text(self) -> str: ...
    @property
    def version(self) -> str: ...
    @property
    def url(self) -> str: ...
    def json(self) -> object: ...

class KoonWebSocket:
    """A WebSocket connection with browser-fingerprinted TLS."""

    async def send(self, data: Union[str, bytes]) -> None: ...
    async def receive(self) -> Optional[dict[str, Union[str, bytes]]]: ...
    async def close(
        self, code: Optional[int] = None, reason: Optional[str] = None
    ) -> None: ...
    async def __aenter__(self) -> "KoonWebSocket": ...
    async def __aexit__(
        self, exc_type: object, exc_val: object, exc_tb: object
    ) -> bool: ...
