from typing import Any, AsyncIterator, Optional, Union

class Koon:
    """Browser impersonation HTTP client with TLS/HTTP2 fingerprint spoofing."""

    def __init__(
        self,
        browser: str = "chrome",
        *,
        profile_json: Optional[str] = None,
        proxy: Optional[str] = None,
        timeout: int = 30000,
        ignore_tls_errors: bool = False,
        headers: Optional[dict[str, str]] = None,
        follow_redirects: bool = True,
        max_redirects: int = 10,
        cookie_jar: bool = True,
        randomize: bool = False,
        session_resumption: bool = True,
        doh: Optional[str] = None,
    ) -> None: ...
    def export_profile(self) -> str: ...
    def save_session(self) -> str: ...
    def load_session(self, json: str) -> None: ...
    def save_session_to_file(self, path: str) -> None: ...
    def load_session_from_file(self, path: str) -> None: ...
    async def get(self, url: str) -> KoonResponse: ...
    async def post(self, url: str, body: Optional[bytes] = None) -> KoonResponse: ...
    async def put(self, url: str, body: Optional[bytes] = None) -> KoonResponse: ...
    async def delete(self, url: str) -> KoonResponse: ...
    async def patch(self, url: str, body: Optional[bytes] = None) -> KoonResponse: ...
    async def head(self, url: str) -> KoonResponse: ...
    async def request(
        self, method: str, url: str, body: Optional[bytes] = None
    ) -> KoonResponse: ...
    async def post_multipart(
        self, url: str, fields: list[dict[str, Any]]
    ) -> KoonResponse: ...
    async def request_streaming(
        self, method: str, url: str, body: Optional[bytes] = None
    ) -> KoonStreamingResponse: ...
    async def websocket(
        self, url: str, headers: Optional[dict[str, str]] = None
    ) -> KoonWebSocket: ...

class KoonResponse:
    """HTTP response from a koon request."""

    @property
    def status(self) -> int: ...
    @property
    def headers(self) -> list[tuple[str, str]]: ...
    @property
    def body(self) -> bytes: ...
    @property
    def text(self) -> str: ...
    @property
    def version(self) -> str: ...
    @property
    def url(self) -> str: ...
    def json(self) -> object: ...

class KoonStreamingResponse:
    """A streaming HTTP response that delivers the body in chunks."""

    @property
    def status(self) -> int: ...
    @property
    def headers(self) -> list[tuple[str, str]]: ...
    @property
    def version(self) -> str: ...
    @property
    def url(self) -> str: ...
    async def next_chunk(self) -> Optional[bytes]: ...
    async def collect(self) -> bytes: ...
    def __aiter__(self) -> AsyncIterator[bytes]: ...
    async def __anext__(self) -> bytes: ...

class KoonWebSocket:
    """A WebSocket connection with browser-fingerprinted TLS."""

    async def send(self, data: Union[str, bytes]) -> None: ...
    async def receive(self) -> Optional[dict[str, Union[str, bytes]]]: ...
    async def close(
        self, code: Optional[int] = None, reason: Optional[str] = None
    ) -> None: ...
    async def __aenter__(self) -> "KoonWebSocket": ...
    async def __aexit__(
        self, exc_type: object, exc_val: object, exc_tb: object
    ) -> bool: ...

class KoonProxy:
    """A local MITM proxy server with browser fingerprinting."""

    @property
    def port(self) -> int: ...
    @property
    def url(self) -> str: ...
    @property
    def ca_cert_path(self) -> str: ...
    @staticmethod
    async def start(
        *,
        browser: str = "chrome",
        profile_json: Optional[str] = None,
        listen_addr: Optional[str] = None,
        header_mode: Optional[str] = None,
        ca_dir: Optional[str] = None,
        timeout: int = 30000,
        randomize: bool = False,
    ) -> "KoonProxy": ...
    def ca_cert_pem(self) -> bytes: ...
    async def shutdown(self) -> None: ...
