# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_koon_wrappers", use_symbols = TRUE, package_name = "koon")

#' @usage NULL
#' @useDynLib koon, .registration = TRUE
NULL

#' List all available browser profile names.
#'
#' @return A character vector of browser profile names.
#' @export
koon_browsers <- function() .Call(wrap__koon_browsers)

Koon <- new.env(parent = emptyenv())

Koon$new <- function(browser, proxy = NULL, proxies = NULL, timeout = NULL, randomize = NULL, headers = NULL, local_address = NULL, on_request = NULL, on_response = NULL, on_redirect = NULL, retries = NULL, locale = NULL, proxy_headers = NULL, ip_version = NULL, follow_redirects = NULL, max_redirects = NULL, cookie_jar = NULL, session_resumption = NULL, ignore_tls_errors = NULL, doh = NULL) .Call(wrap__Koon__new, browser, proxy, proxies, timeout, randomize, headers, local_address, on_request, on_response, on_redirect, retries, locale, proxy_headers, ip_version, follow_redirects, max_redirects, cookie_jar, session_resumption, ignore_tls_errors, doh)

Koon$get <- function(url, headers = NULL) .Call(wrap__Koon__get, self, url, headers)

Koon$post <- function(url, body = NULL, headers = NULL) .Call(wrap__Koon__post, self, url, body, headers)

Koon$put <- function(url, body = NULL, headers = NULL) .Call(wrap__Koon__put, self, url, body, headers)

Koon$delete <- function(url, headers = NULL) .Call(wrap__Koon__delete, self, url, headers)

Koon$patch <- function(url, body = NULL, headers = NULL) .Call(wrap__Koon__patch, self, url, body, headers)

Koon$head <- function(url, headers = NULL) .Call(wrap__Koon__head, self, url, headers)

Koon$save_session <- function() .Call(wrap__Koon__save_session, self)

Koon$load_session <- function(json) invisible(.Call(wrap__Koon__load_session, self, json))

Koon$export_profile <- function() .Call(wrap__Koon__export_profile, self)

Koon$total_bytes_sent <- function() .Call(wrap__Koon__total_bytes_sent, self)

Koon$total_bytes_received <- function() .Call(wrap__Koon__total_bytes_received, self)

Koon$reset_counters <- function() invisible(.Call(wrap__Koon__reset_counters, self))

Koon$user_agent <- function() .Call(wrap__Koon__user_agent, self)

Koon$clear_cookies <- function() invisible(.Call(wrap__Koon__clear_cookies, self))

#' @export
`$.Koon` <- function (self, name) { func <- Koon[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Koon` <- `$.Koon`


# nolint end
