# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_koon_wrappers", use_symbols = TRUE, package_name = "koon")

#' @usage NULL
#' @useDynLib koon, .registration = TRUE
NULL

#' List all available browser profile names.
#'
#' @return A character vector of browser profile names.
#' @export
koon_browsers <- function() .Call(wrap__koon_browsers)

Koon <- new.env(parent = emptyenv())

Koon$new <- function(browser, proxy = NULL, timeout = NULL, randomize = NULL, headers = NULL) .Call(wrap__Koon__new, browser, proxy, timeout, randomize, headers)

Koon$get <- function(url) .Call(wrap__Koon__get, self, url)

Koon$post <- function(url, body = NULL) .Call(wrap__Koon__post, self, url, body)

Koon$put <- function(url, body = NULL) .Call(wrap__Koon__put, self, url, body)

Koon$delete <- function(url) .Call(wrap__Koon__delete, self, url)

Koon$patch <- function(url, body = NULL) .Call(wrap__Koon__patch, self, url, body)

Koon$head <- function(url) .Call(wrap__Koon__head, self, url)

Koon$save_session <- function() .Call(wrap__Koon__save_session, self)

Koon$load_session <- function(json) invisible(.Call(wrap__Koon__load_session, self, json))

Koon$export_profile <- function() .Call(wrap__Koon__export_profile, self)

#' @export
`$.Koon` <- function (self, name) { func <- Koon[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Koon` <- `$.Koon`


# nolint end
