# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib koon, .registration = TRUE
NULL

# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_koon_wrappers", use_symbols = TRUE, package_name = "koon")

#' @usage NULL
#' @useDynLib koon, .registration = TRUE
NULL

#' List all available browser profile names
#'
#' One name per profile: every browser version on every OS it has a profile
#' for, e.g. `"chrome154-windows"`, `"safari266-ios"` or `"okhttp5"`. Names
#' without a version select the latest one (`"chrome-macos"`); without an
#' OS, desktop profiles impersonate Windows, Safari macOS (`"firefox154"`).
#'
#' @return A character vector of browser profile names.
#' @export
koon_browsers <- function() .Call(wrap__koon_browsers)

#' Raise the user interrupt that stopped a request.
#' @noRd
raise_interrupt <- function() invisible(.Call(wrap__raise_interrupt))

Koon <- new.env(parent = emptyenv())

Koon$new <- function(browser = "chrome", profile_json = NULL, proxy = NULL, proxies = NULL, timeout = NULL, headers = NULL, local_address = NULL, on_request = NULL, on_response = NULL, on_redirect = NULL, retries = NULL, locale = NULL, proxy_headers = NULL, ip_version = NULL, follow_redirects = NULL, max_redirects = NULL, cookie_jar = NULL, session_resumption = NULL, ignore_tls_errors = NULL, proxy_ca_certs = NULL, ignore_proxy_tls_errors = NULL, doh = NULL, resolve = NULL, max_response_body = NULL, server_padding = NULL) .Call(wrap__Koon__new, browser, profile_json, proxy, proxies, timeout, headers, local_address, on_request, on_response, on_redirect, retries, locale, proxy_headers, ip_version, follow_redirects, max_redirects, cookie_jar, session_resumption, ignore_tls_errors, proxy_ca_certs, ignore_proxy_tls_errors, doh, resolve, max_response_body, server_padding)

Koon$request <- function(method, url, body = NULL, headers = NULL, timeout = NULL, proxy = NULL, follow_redirects = NULL, max_redirects = NULL, on_request = NULL, on_response = NULL, on_redirect = NULL) .Call(wrap__Koon__request, self, method, url, body, headers, timeout, proxy, follow_redirects, max_redirects, on_request, on_response, on_redirect)

Koon$save_session <- function() .Call(wrap__Koon__save_session, self)

Koon$load_session <- function(json) .Call(wrap__Koon__load_session, self, json)

Koon$set_cookies <- function(cookies) .Call(wrap__Koon__set_cookies, self, cookies)

Koon$cookies <- function() .Call(wrap__Koon__cookies, self)

Koon$export_profile <- function() .Call(wrap__Koon__export_profile, self)

Koon$total_bytes_sent <- function() .Call(wrap__Koon__total_bytes_sent, self)

Koon$total_bytes_received <- function() .Call(wrap__Koon__total_bytes_received, self)

Koon$reset_counters <- function() invisible(.Call(wrap__Koon__reset_counters, self))

Koon$user_agent <- function() .Call(wrap__Koon__user_agent, self)

Koon$clear_cookies <- function() invisible(.Call(wrap__Koon__clear_cookies, self))

Koon$close <- function() invisible(.Call(wrap__Koon__close, self))

Koon$shutdown <- function() invisible(.Call(wrap__Koon__shutdown, self))

#' @export
`$.Koon` <- function (self, name) { func <- Koon[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Koon` <- `$.Koon`

# nolint end
