test_that("sessions save and load, also from readLines()", {
  base <- test_server_url()
  client <- Koon$new()
  client$get(paste0(base, "/set-cookie"))
  session <- client$save_session()
  restored <- Koon$new()
  expect_null(restored$load_session(session))
  expect_match(restored$get(paste0(base, "/cookies"))$text, "session=abc123")
  expect_koon_error(restored$load_session("{not json"), "JSON_ERROR")
  expect_koon_error(restored$load_session(c("a", "b")), "JSON_ERROR")
  expect_koon_error(restored$load_session(1), "INVALID_ARGUMENT")
  path <- withr::local_tempfile(fileext = ".json")
  writeLines(session, path)
  from_file <- Koon$new()
  from_file$load_session(readLines(path))
  expect_match(from_file$get(paste0(base, "/cookies"))$text, "session=abc123")

  expect_gt(client$total_bytes_sent(), 0)
  expect_gt(client$total_bytes_received(), 0)
  client$reset_counters()
  expect_identical(client$total_bytes_sent(), 0)
})

test_that("profiles export, load and list", {
  client <- Koon$new()
  profile <- jsonlite::fromJSON(client$export_profile(), simplifyVector = FALSE)
  expect_true("tls" %in% names(profile))
  from_json <- Koon$new(profile_json = client$export_profile())
  expect_identical(from_json$user_agent(), client$user_agent())
  expect_match(client$user_agent(), "Windows NT")
  expect_match(Koon$new("chrome-macos")$user_agent(), "Macintosh")
  expect_match(Koon$new("safari")$user_agent(), "Macintosh")

  browsers <- koon_browsers()
  expect_true(all(c("chrome154-windows", "opera136-linux", "safari266-ios", "okhttp5") %in% browsers))
  expect_false(anyDuplicated(browsers) > 0)
  for (name in browsers) expect_s3_class(Koon$new(name), "Koon")
})
