//! The root certificates koon verifies server certificates against: one store per profile,
//! Mozilla's roots plus every trust anchor of the embedded Chrome Root Store versions, deduplicated
//! (which roots a browser trusts does not show on the wire, so the union loses nothing). What a
//! profile advertises stays per version ([`chrome_trust_anchor_ids`]).

use std::collections::HashSet;
use std::sync::OnceLock;

use base64::Engine;
use btls::hash::{MessageDigest, hash};
use btls::ssl::SslContextBuilder;
use btls::x509::X509;
use btls::x509::store::{X509Store, X509StoreBuilder};
use btls::x509::verify::X509VerifyFlags;

use super::config::TrustAnchorId;
use crate::Error;

// Generated by `cargo test -p koon-core --test chrome_root_store -- --ignored` (see
// tests/chrome_root_store.rs), which records the Chromium sources.
#[rustfmt::skip]
mod chrome_root_store;

/// A TLS trust anchor of the Chrome Root Store: a root of `trust_anchors` or an intermediate of
/// `additional_certs` marked `tls_trust_anchor`.
struct ChromeAnchor {
    /// SHA-256 of the certificate, hex.
    sha256: &'static str,
    /// Its trust anchor ID (draft-ietf-tls-trust-anchor-ids), a relative OID below 1.3.6.1.4.1;
    /// empty for none.
    trust_anchor_id: &'static [u8],
    /// The stores it belongs to: bit `i` stands for `RELEASES[i]`.
    stores: u32,
    /// The certificate, DER in base64.
    der: &'static str,
}

/// Hex-encode `bytes` (lowercase, no separator).
fn hex(bytes: &[u8]) -> String {
    use std::fmt::Write;
    bytes
        .iter()
        .fold(String::with_capacity(bytes.len() * 2), |mut s, b| {
            let _ = write!(s, "{b:02x}");
            s
        })
}

/// Mozilla's roots and the embedded Chrome anchors, each certificate once (by SHA-256), parsed.
fn certs() -> &'static [X509] {
    static CERTS: OnceLock<Vec<X509>> = OnceLock::new();
    CERTS.get_or_init(|| {
        let mozilla = webpki_root_certs::TLS_SERVER_ROOT_CERTS;
        let mozilla_digests: HashSet<String> = mozilla
            .iter()
            .map(|der| {
                let digest =
                    hash(MessageDigest::sha256(), der.as_ref()).expect("SHA-256 of a certificate");
                hex(&digest)
            })
            .collect();
        let chrome_only = chrome_root_store::ANCHORS
            .iter()
            .filter(|anchor| !mozilla_digests.contains(anchor.sha256))
            .map(|anchor| {
                let der = base64::engine::general_purpose::STANDARD
                    .decode(anchor.der)
                    .expect("embedded Chrome Root Store certificate is base64");
                X509::from_der(&der).expect("embedded Chrome Root Store certificate parses")
            });
        mozilla
            .iter()
            .filter_map(|der| X509::from_der(der.as_ref()).ok())
            .chain(chrome_only)
            .collect()
    })
}

/// A new store with the certificates of [`certs`] and `extra`.
fn build(extra: &[X509]) -> Result<X509Store, Error> {
    let mut builder = X509StoreBuilder::new()?;
    for cert in certs().iter().chain(extra) {
        builder.add_cert(cert)?;
    }
    // Chrome trusts the intermediates of its store as anchors of their own: a chain that reaches
    // one is trusted without its root. BoringSSL, like Chrome for these anchors, still checks their
    // validity period and constraints.
    builder.set_flags(X509VerifyFlags::PARTIAL_CHAIN);
    Ok(builder.build())
}

/// Verify the certificates of `builder`'s connections against koon's store. All contexts share one
/// `X509Store`.
pub fn load(builder: &mut SslContextBuilder) -> Result<(), Error> {
    static SHARED: OnceLock<X509Store> = OnceLock::new();
    let shared = match SHARED.get() {
        Some(shared) => shared.clone(),
        None => {
            let built = build(&[])?;
            SHARED.get_or_init(|| built).clone()
        }
    };
    builder.set_verify_cert_store(shared)?;
    Ok(())
}

/// A new store with koon's certificates plus `extra` (the CAs of an HTTPS proxy).
pub fn with_extra(extra: &[X509]) -> Result<X509Store, Error> {
    build(extra)
}

/// The trust anchor IDs Chrome `major` sends, sorted bytewise as Chromium 154 sends them: the IDs
/// of the roots and of the intermediates trusted as anchors in the store that release ships
/// (Chromium `GetTrustAnchorIDsFromCompiledInRootStore`). `None` if that store is not embedded.
pub fn chrome_trust_anchor_ids(major: u32) -> Option<Vec<TrustAnchorId>> {
    let index = chrome_root_store::RELEASES
        .iter()
        .position(|&(chrome, _)| chrome == major)?;
    let mut ids: Vec<TrustAnchorId> = chrome_root_store::ANCHORS
        .iter()
        .filter(|anchor| anchor.stores & (1 << index) != 0 && !anchor.trust_anchor_id.is_empty())
        .map(|anchor| TrustAnchorId::from_static(anchor.trust_anchor_id))
        .collect();
    ids.sort_unstable();
    Some(ids)
}

#[cfg(test)]
mod tests {
    use btls::asn1::Asn1Time;
    use btls::bn::{BigNum, MsbOption};
    use btls::ec::{EcGroup, EcKey};
    use btls::hash::MessageDigest;
    use btls::nid::Nid;
    use btls::pkey::{PKey, Private};
    use btls::stack::Stack;
    use btls::x509::extension::BasicConstraints;
    use btls::x509::{X509Builder, X509NameBuilder, X509StoreContext};

    use super::*;

    fn sha256(cert: &X509) -> String {
        hex(&cert.digest(MessageDigest::sha256()).unwrap())
    }

    #[test]
    fn embedded_anchors_match_their_digests() {
        for anchor in &chrome_root_store::ANCHORS {
            let der = base64::engine::general_purpose::STANDARD
                .decode(anchor.der)
                .unwrap();
            assert_eq!(sha256(&X509::from_der(&der).unwrap()), anchor.sha256);
            assert!(anchor.trust_anchor_id.len() < 256, "{}", anchor.sha256);
            assert!(anchor.stores >> chrome_root_store::RELEASES.len() == 0);
        }
    }

    /// The store holds every Mozilla root and every Chrome anchor, each once, among them roots only
    /// Mozilla still trusts (DigiCert Global Root CA, COMODO Certification Authority) and
    /// intermediates only Chrome trusts as anchors (Google Trust Services WE2).
    #[test]
    fn the_store_is_the_union_of_mozilla_and_chrome() {
        let digests: HashSet<String> = certs().iter().map(sha256).collect();
        assert_eq!(digests.len(), certs().len(), "duplicates");
        for der in webpki_root_certs::TLS_SERVER_ROOT_CERTS {
            let digest = hex(&btls::hash::hash(MessageDigest::sha256(), der.as_ref()).unwrap());
            assert!(digests.contains(&digest), "Mozilla root {digest}");
        }
        for anchor in &chrome_root_store::ANCHORS {
            assert!(
                digests.contains(anchor.sha256),
                "Chrome anchor {}",
                anchor.sha256
            );
        }
        let subjects: Vec<String> = certs()
            .iter()
            .map(|cert| {
                cert.subject_name()
                    .entries_by_nid(Nid::COMMONNAME)
                    .map(|e| e.data().as_utf8().unwrap().to_string())
                    .collect()
            })
            .collect();
        for name in [
            "DigiCert Global Root CA",
            "COMODO Certification Authority",
            "WE2",
        ] {
            assert!(subjects.iter().any(|s| s == name), "{name}");
        }
    }

    /// Chrome 152 sends the 32 IDs of Chrome Root Store version 36; 153 and 154 the 28 of versions
    /// 38 and 39.
    #[test]
    fn trust_anchor_ids_per_chrome_release() {
        let count = |major| chrome_trust_anchor_ids(major).map(|ids| ids.len());
        assert_eq!(count(152), Some(32));
        assert_eq!(count(153), Some(28));
        assert_eq!(count(154), Some(28));
        assert_eq!(count(151), None);
        let google_wr5 = TrustAnchorId::from_static(&[0xd6, 0x79, 0x09, 0x09]);
        // WR5 left the store with version 38.
        assert!(chrome_trust_anchor_ids(152).unwrap().contains(&google_wr5));
        assert!(!chrome_trust_anchor_ids(153).unwrap().contains(&google_wr5));
    }

    fn key() -> PKey<Private> {
        let group = EcGroup::from_curve_name(Nid::X9_62_PRIME256V1).unwrap();
        PKey::from_ec_key(EcKey::generate(&group).unwrap()).unwrap()
    }

    fn cert(
        name: &str,
        ca: bool,
        key: &PKey<Private>,
        issuer: Option<(&X509, &PKey<Private>)>,
    ) -> X509 {
        let mut subject = X509NameBuilder::new().unwrap();
        subject.append_entry_by_nid(Nid::COMMONNAME, name).unwrap();
        let subject = subject.build();
        let mut builder = X509Builder::new().unwrap();
        builder.set_version(2).unwrap();
        let mut serial = BigNum::new().unwrap();
        serial.rand(64, MsbOption::MAYBE_ZERO, false).unwrap();
        builder
            .set_serial_number(&serial.to_asn1_integer().unwrap())
            .unwrap();
        builder.set_subject_name(&subject).unwrap();
        builder
            .set_issuer_name(issuer.map_or(&*subject, |(c, _)| c.subject_name()))
            .unwrap();
        builder.set_pubkey(key).unwrap();
        builder
            .set_not_before(&Asn1Time::days_from_now(0).unwrap())
            .unwrap();
        builder
            .set_not_after(&Asn1Time::days_from_now(30).unwrap())
            .unwrap();
        if ca {
            let constraints = BasicConstraints::new().critical().ca().build().unwrap();
            builder.append_extension(&constraints).unwrap();
        }
        let signer = issuer.map_or(key, |(_, k)| k);
        builder.sign(signer, MessageDigest::sha256()).unwrap();
        builder.build()
    }

    fn verifies(store: &X509Store, leaf: &X509) -> bool {
        let mut ctx = X509StoreContext::new().unwrap();
        ctx.init(store, leaf, &Stack::new().unwrap(), |c| c.verify_cert())
            .unwrap()
    }

    /// A chain that ends at an intermediate of the store verifies without its root, as in Chrome.
    #[test]
    fn intermediates_of_the_store_are_anchors() {
        let (root_key, intermediate_key, leaf_key) = (key(), key(), key());
        let root = cert("root", true, &root_key, None);
        let intermediate = cert(
            "intermediate",
            true,
            &intermediate_key,
            Some((&root, &root_key)),
        );
        let leaf = cert(
            "leaf",
            false,
            &leaf_key,
            Some((&intermediate, &intermediate_key)),
        );

        let store = with_extra(std::slice::from_ref(&intermediate)).unwrap();
        assert!(verifies(&store, &leaf));
        assert!(!verifies(&with_extra(&[]).unwrap(), &leaf));
    }
}
